# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


  Creator.create(name:"Meghan")
  Creator.create(name:"Esther")
  Creator.create(name:"Adam")
  Creator.create(name:"Gavin")

  Reception.create(name:"Meghan's Wedding", date:"October 15, 2019", creator_id: 1)
  Reception.create(name:"Esther's Wedding", date:"November 1, 2019", creator_id: 2)
  Reception.create(name:"Adam's Wedding", date:"September 20, 2019", creator_id: 3)
  Reception.create(name:"Gavin's Wedding", date:"December 24, 2019", creator_id: 4)

  Guest.create(name:"Ann", rsvp:true, reception_id: 1, password: '123', email: 'ann@gmail.com')
  Guest.create(name:"Steve", rsvp:true, reception_id: 1, password: '123', email: 'steve@gmail.com')
  Guest.create(name:"Marty", rsvp:false, reception_id: 1, password: '123', email: 'marty@gmail.com')
  Guest.create(name:"Helga", rsvp:true, reception_id: 1, password: '123', email: 'helga@gmail.com')
  Guest.create(name:"Shirley", rsvp:true, reception_id: 2, password: '123', email: 'shirley@gmail.com')
  Guest.create(name:"Bob", rsvp:false, reception_id: 2, password: '123', email: 'bob@gmail.com')
  Guest.create(name:"Ruth", rsvp:true, reception_id: 2, password: '123', email: 'ruth@gmail.com')
  Guest.create(name:"Leanne", rsvp:true, reception_id: 2, password: '123', email: 'leanne@gmail.com')
  Guest.create(name:"Chris", rsvp:false, reception_id: 3, password: '123', email: 'chris@gmail.com')
  Guest.create(name:"Jacob", rsvp:true, reception_id: 3, password: '123', email: 'jacob@gmail.com')
  Guest.create(name:"Jennifer", rsvp:true, reception_id: 3, password: '123', email: 'jennifer@gmail.com')
  Guest.create(name:"Gabby", rsvp:true, reception_id: 3, password: '123', email: 'gabby@gmail.com')
  Guest.create(name:"John", rsvp:true, reception_id: 4, password: '123', email: 'john@gmail.com')
  Guest.create(name:"Ashley", rsvp:false, reception_id: 4, password: '123', email: 'ashley@gmail.com')
  Guest.create(name:"Adam", rsvp:true, reception_id: 4, password: '123', email: 'adam@gmail.com')
  Guest.create(name:"Esther", rsvp:true, reception_id: 4, password: '123', email: 'esther@gmail.com')

  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGLR4RXGd8Byx6gZyc2CtCh7RZXgJIoRW3ZtBzlU2m7WQprMh-nQ", imageable_id: 1, imageable_type: "Creator", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEn5C8gO1YL9HpTzzl1h3PgoxW8cxRCSBbMo7GAMtLTgo4QTokhw", imageable_id: 1, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTld3QtvGAfSj84f29HfoLGXWnXkyQzsH5Ng-IIpsm7eljQJ3M-", imageable_id: 2, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2fXhHx8FWz4PZYPZW7yFtNCOm6mEQgKWcWe1uwgAmz2BMxjtW", imageable_id: 2, imageable_type: "Creator", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2CEM8IWJWlMD7ejHaMoxqbs86dHJqItgwL4l_pbBIdfzt_u6A", imageable_id: 3, imageable_type: "Creator", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ64jaK64UXB9YtrCOAeYEdJVUCzharlBtzVKMYA6u0G1KS5uTAAg", imageable_id: 3, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2fgJM0ucjVrDFOzPUJOS1YEiQbKv5Vz3RvbdqYQKDIChA979E", imageable_id: 3, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStqkXe2l-GUIDy2hOy91Y4mZWDf4H-Z7z6jomG4Z5uJ18jzRIoGg", imageable_id: 4, imageable_type: "Creator", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCQn-2lS66J2LpgjP2F881-4kzf3A9NAbFS256O7EAMM6mTc8T", imageable_id: 4, imageable_type: "Creator", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm3BOO6keZiYSgTNvRkh5ShV2NyTr1Ee-vgXnow_GsgrTYFp6k", imageable_id: 4, imageable_type: "Creator", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXW6bAU8L8V_sHRghGLYHkvAIhoXihQebDosMgruSnj_EZ3dFW", imageable_id: 5, imageable_type: "Guest", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvi-nDarouAuKP-kSypNyG4zEraaW4UeGLaQgRXw3T8MPnelNaQQ", imageable_id: 5, imageable_type: "Guest", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShZck8rCRKa7qbT-pvoY31apNkX2RpO7RvqmxPcYFxVM_MLnbS", imageable_id: 6, imageable_type: "Guest", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc6LFoUiaQN1HhMYmUsS4wTID6DphkOSdqT6zarqcZMV0PhCnzaw", imageable_id: 6, imageable_type: "Guest", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG_67YidAbX5iDAFukHrfOCNKlUR1s8I8AcxY8JydjtkHrT_g-Bw", imageable_id: 7, imageable_type: "Creator", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTzYPYAiCl-lgm4AmNIpjGOwgqnUxfQNZvPvSCSDcp8Jzu44Kb7g", imageable_id: 7, imageable_type: "Guest", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-TIF2hM8tblqn4nLtoGC-SrLcoJiHZJLdF95UXBvg7gcTSqDm", imageable_id: 8, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuDRauRrBGxRSbMIPwoh2zZt-LIRyczi98Jo-uvziyHY-t1rdk", imageable_id: 8, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXAvCWf4PYOL1y783fQ2gnV_23XSlEpKb5-V1_RSZk-8XmTMz1DQ", imageable_id: 9, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE_aJ2NLapiU-tdVC0EkelahviEbfcFclY-bRv2ef0lLLTeTBUZw", imageable_id: 9, imageable_type: "Creator", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqzixQKNM_t6WogJOH7iM0eyikUd1b-OPqPZNqckSFlEEJJatK", imageable_id: 9, imageable_type: "Creator", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZ13UNiPlawxbiTaulSgpT6xOS8pExyL6KqsoIbwOakGHi2lOh", imageable_id: 10, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDAyi2GBXkXpKxXn-aswHrSCTwFwUIPklahsGL31ZR6NqSOr1t", imageable_id: 10, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIxB4QS7RviPGKRoqa_j2AKiTZqZOIXZiY7ukSRfYHbojVusc3", imageable_id: 11, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSGcbRYJ8ge3tt5clvW9_ESEG9_S4omxTa_fOLmlU2MdETrKRudw", imageable_id: 11, imageable_type: "Guest", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT81duMx8IU71nUlD_MbaITEPeWY7l4sKxmKKvvdC1-Rs3-D97LtA", imageable_id: 12, imageable_type: "Creator", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo36CcO4edQA4DuPjIoCAC58hThdABLeFN_e2gIule3-LNzgjQ", imageable_id: 12, imageable_type: "Creator", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOycgL0DBZCdAOiKTwwNudfmpkUJzqLqdUOBUwXoBXDP2ix77TbA", imageable_id: 13, imageable_type: "Guest", reception_id: 3)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpJ1Ie0dFOaOzKSjRwleCAkx8GWw4IhTbNAFCtYVq1FVkxT2uo", imageable_id: 13, imageable_type: "Guest", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDuy1YK7L59sRdCLx58ma9sQcIVE7gtBiK1cIU-r5jXFeMo9QX", imageable_id: 13, imageable_type: "Guest", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbZXQwdwvTlSSu3u5U2Z_Uurhm6HoT7Vhk22wEwPCWanfccq5oLA", imageable_id: 14, imageable_type: "Guest", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7j-nW-pwvzuJTt8JCOkIBMpG3fx4bvxm4A0IfV3yT4w41X2Y61A", imageable_id: 14, imageable_type: "Creator", reception_id: 4)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ9TD4fB_39AotIpfJ_2trN9EtSIOZZAbvddUG1zHse7pKu05HHw", imageable_id: 14, imageable_type: "Creator", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YPRjG0T44H1wbFVXZHsNrWFiYETtlr5Z1miA35LVZDp9QsI1Jw", imageable_id: 15, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc5KALW8H5WglXr6ln3hQ-XJx7fB20lSUBCe6OBW-31nfwrixRgg", imageable_id: 15, imageable_type: "Guest", reception_id: 1)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8GEFo9srFxgV5P94butnEp3eH_c8a-UNMQgDkvSYLbEL34Qej", imageable_id: 15, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcmi1djcMBGwfiGAz7As69Qfy_0ih_gMJLAs8r93rT5NX8Xu78", imageable_id: 16, imageable_type: "Guest", reception_id: 2)
  Photo.create(image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj_g6JhXseIN-E2s82td-vq5UdQpTJCPuoVz3lcEQ6-pbEuslt", imageable_id: 16, imageable_type: "Creator", reception_id: 2)

  Comment.create(content:"Wishing you a lifetime of love and happiness.", commentable_id: 1, commentable_type: "Guest", reception_id: 1)
  Comment.create(content:"On your rollercoaster ride through life together, may you high five at all the right places and support each other through every twist and turn.", commentable_id: 1, commentable_type: "Guest", reception_id: 1)
  Comment.create(content:"With warmest wishes on your wedding day and always.", commentable_id: 2, commentable_type: "Guest", reception_id: 1)
  Comment.create(content:"Your wedding day will come and go, but may your love forever grow.", commentable_id: 2, commentable_type: "Guest", reception_id: 1)
  Comment.create(content:"Best wishes on this wonderful journey, as you build your new lives together.", commentable_id: 3, commentable_type: "Creator", reception_id: 1)
  Comment.create(content:"We are so happy to celebrate your special day with you, what a wonderful addition to the family!", commentable_id: 3, commentable_type: "Creator", reception_id: 1)
  Comment.create(content:"You have shared so much love and laughter over your years together, and I know there will be many more joyful moments to come. I wish you all the happiness that you deserve for your married life together.", commentable_id: 4, commentable_type: "Guest", reception_id: 1)
  Comment.create(content:"May the years ahead be filled with lasting joy.", commentable_id: 4, commentable_type: "Guest", reception_id: 1)
  Comment.create(content:"May the love you feel for each other today grow ever stronger and more fulfilling as the years go by.", commentable_id: 5, commentable_type: "Guest", reception_id: 2)
  Comment.create(content:"There is no couple more deserving of a joyful and loving wedding day as you two.", commentable_id: 5, commentable_type: "Guest", reception_id: 2)
  Comment.create(content:"Thank you for letting us/me share in this joyful day. We/I wish you all the best as you embark on this wonderful union.", commentable_id: 6, commentable_type: "Guest", reception_id: 2)
  Comment.create(content:"Thanks for inviting us to eat and drink while you get married. Congrats!", commentable_id: 6, commentable_type: "Guest", reception_id: 2)
  Comment.create(content:"Our marriage advice: Love, honor and… scrub the toilet.", commentable_id: 7, commentable_type: "Creator", reception_id: 2)
  Comment.create(content:"I can’t believe my best friend is getting married! ", commentable_id: 7, commentable_type: "Creator", reception_id: 2)
  Comment.create(content:"Thanks for the free booze. Best wishes on a long, happy marriage!", commentable_id: 8, commentable_type: "Guest", reception_id: 2)
  Comment.create(content:"We love you, you beautiful people, congrats!", commentable_id: 8, commentable_type: "Guest", reception_id: 2)
  Comment.create(content:"We’re delighted to share this day with you both.", commentable_id: 9, commentable_type: "Guest", reception_id: 3)
  Comment.create(content:"What a wonderful day for our family, and especially you two. May the joy you feel today last a lifetime.", commentable_id: 9, commentable_type: "Guest", reception_id: 3)
  Comment.create(content:"Congratulations, you two weirdos were made for each other!", commentable_id: 10, commentable_type: "Guest", reception_id: 3)
  Comment.create(content:"Today, we add one more member to our family, and we couldn’t be happier. Best wishes to you both.", commentable_id: 10, commentable_type: "Guest", reception_id: 3)
  Comment.create(content:"Woohoo, you got married! Wishing you two lovebirds a lifetime of Netflix binging", commentable_id: 11, commentable_type: "Creator", reception_id: 3)
  Comment.create(content:"Your wedding day may come and go, but may your love forever grow. Congratulations to the perfect couple!", commentable_id: 11, commentable_type: "Creator", reception_id: 3)
  Comment.create(content:"Congratulations on tying the knot!", commentable_id: 12, commentable_type: "Guest", reception_id: 3)
  Comment.create(content:"You guys are great together. So happy for you two!", commentable_id: 12, commentable_type: "Guest", reception_id: 3)
  Comment.create(content:"Seeing you two make promises and step forward into the future is so inspiring and wonderful.", commentable_id: 13, commentable_type: "Guest", reception_id: 4)
  Comment.create(content:"So happy to celebrate this day with you both!", commentable_id: 13, commentable_type: "Guest", reception_id: 4)
  Comment.create(content:"Best wishes for a fun-filled future together.", commentable_id: 14, commentable_type: "Guest", reception_id: 4)
  Comment.create(content:"hank you for letting me share in this joyful day.", commentable_id: 14, commentable_type: "Creator", reception_id: 4)
  Comment.create(content:"As Bill and Ted said, ‘Be excellent to each other.’", commentable_id: 15, commentable_type: "Creator", reception_id: 4)
  Comment.create(content:"I’m so happy to call you both my friends.", commentable_id: 15, commentable_type: "Guest", reception_id: 4)
  Comment.create(content:"Here’s to love and friendship.", commentable_id: 16, commentable_type: "Guest", reception_id: 4)
  Comment.create(content:"We’re delighted to share this day with you.", commentable_id: 16, commentable_type: "Guest", reception_id: 4)
